---
title: Laird Streak Developer Geek
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: lairdstreak@gmail.com
description: Ramblings of a Developer / Coder, husband and father sometimes gamer
  and wanna be artsy guy.
baseurl: ''
url: https://lairdstreak.github.io
twitter_username: lairdstreak
github_username: lairdstreak
copy_data: Copyright @me
markdown: kramdown
future: true
