---
title: grim93 Developer Geek
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: lairdstreak@gmail.com
description: Ramblings of a Developer / Coder, husband and father sometimes gamer
  and wanna be artsy guy.
baseurl: ''
url: https://grim93.github.io
twitter_username: lairdstreak
github_username: grim93
copy_data: Copyright @me
markdown: kramdown
future: true
