# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: grim93 Developer Geek
email: lairdstreak@gmail.com
description: "Ramblings of a Developer / Coder, husband and father sometimes gamer and wanna be artsy guy."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://grim93.github.io" # the base hostname & protocol for your site
twitter_username: lairdstreak
github_username:  grim93
copy_data: "Copyright @me"

# Build settings
markdown: kramdown
# future
future: true

#theme: jekyll-theme-modernist