# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Grim 93
email: lairdstreak@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ramblings of a Code Jockey, husband and father.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://grim93.github.io" # the base hostname & protocol for your site
twitter_username: lairdstreak
github_username:  grim93

# Build settings
markdown: kramdown
# future
future: true

#theme: jekyll-theme-modernist